doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%env(DATABASE_HOST)%'
        port: '%env(int:DATABASE_PORT)%'
        dbname: '%env(DATABASE_NAME)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        server_version: '%env(DATABASE_SERVER_VERSION)%'
        charset: UTF8
        profiling_collect_backtrace: '%kernel.debug%'
        logging: false
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
