<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261007020000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Versioned commission formulas, immutable rule history and calculation snapshots.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE commission_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by_id INT DEFAULT NULL, settings JSON NOT NULL, reason VARCHAR(2000) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3496B2EB03A8386 ON commission_rule (created_by_id)');
        $this->addSql('ALTER TABLE commission_rule ADD CONSTRAINT FK_COMMISSION_RULE_ACTOR FOREIGN KEY (created_by_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("INSERT INTO commission_rule (settings, reason, created_at) VALUES ('{\"percentage\":\"80.0000\",\"basis\":\"margin_psd\",\"psdRegion\":1,\"subtractFreight\":true,\"applyReferenceDiscount\":false}', 'Regra inicial: 80% da margem PSD, região 1, descontando frete. Validar com o administrador antes de operar.', CURRENT_TIMESTAMP)");
        $this->addSql("CREATE FUNCTION gcom_protect_commission_rule() RETURNS trigger LANGUAGE plpgsql AS 'BEGIN RAISE EXCEPTION ''Commission rule history is immutable''; END;'");
        $this->addSql('CREATE TRIGGER immutable_commission_rule BEFORE UPDATE OR DELETE ON commission_rule FOR EACH ROW EXECUTE FUNCTION gcom_protect_commission_rule()');
        $this->addSql("CREATE FUNCTION gcom_protect_calculation() RETURNS trigger LANGUAGE plpgsql AS 'BEGIN IF NEW.calculation::jsonb IS DISTINCT FROM OLD.calculation::jsonb OR NEW.gross_amount IS DISTINCT FROM OLD.gross_amount OR NEW.deductions IS DISTINCT FROM OLD.deductions OR NEW.net_amount IS DISTINCT FROM OLD.net_amount THEN RAISE EXCEPTION ''Commission calculation is immutable''; END IF; RETURN NEW; END;'");
        $this->addSql('CREATE TRIGGER immutable_commission_calculation BEFORE UPDATE ON commission FOR EACH ROW EXECUTE FUNCTION gcom_protect_calculation()');
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException('Financial calculation history.');
    }
}
