<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261007000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Users, immutable orders/items, commissions, deductions, payment links and audit trail.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(120) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE commission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(40) NOT NULL, customer_code VARCHAR(30) NOT NULL, customer_name VARCHAR(200) NOT NULL, gross_amount NUMERIC(18, 2) NOT NULL, deductions NUMERIC(18, 2) NOT NULL, net_amount NUMERIC(18, 2) NOT NULL, status VARCHAR(20) NOT NULL, calculation JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, approved_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1C65015877153098 ON commission (code)');
        $this->addSql('CREATE INDEX IDX_1C650158B03A8386 ON commission (created_by_id)');
        $this->addSql('CREATE INDEX IDX_1C6501582D234F6A ON commission (approved_by_id)');
        $this->addSql('CREATE TABLE audit_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(80) NOT NULL, subject VARCHAR(120) NOT NULL, details JSON NOT NULL, request_id VARCHAR(64) NOT NULL, ip VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3CE56E5010DAF24A ON audit_event (actor_id)');
        $this->addSql('CREATE TABLE order_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_number VARCHAR(30) NOT NULL, customer_code VARCHAR(30) NOT NULL, customer_name VARCHAR(200) NOT NULL, total NUMERIC(18, 2) NOT NULL, captured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, header JSON NOT NULL, commission_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CDB5F784551F0F81 ON order_snapshot (order_number)');
        $this->addSql('CREATE INDEX IDX_CDB5F784202D1EB2 ON order_snapshot (commission_id)');
        $this->addSql('CREATE TABLE adjustment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_code VARCHAR(30) NOT NULL, type VARCHAR(20) NOT NULL, amount NUMERIC(18, 2) NOT NULL, reason TEXT NOT NULL, source_reference VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commission_id INT DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_89F97816202D1EB2 ON adjustment (commission_id)');
        $this->addSql('CREATE INDEX IDX_89F97816B03A8386 ON adjustment (created_by_id)');
        $this->addSql('CREATE TABLE payment_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, routine VARCHAR(80) NOT NULL, reference VARCHAR(100) NOT NULL, amount NUMERIC(18, 2) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, verification VARCHAR(30) NOT NULL, notes TEXT NOT NULL, commission_id INT NOT NULL, confirmed_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_172F0E85202D1EB2 ON payment_link (commission_id)');
        $this->addSql('CREATE UNIQUE INDEX payment_routine_reference_unique ON payment_link (routine, reference)');
        $this->addSql('CREATE INDEX IDX_172F0E856F45385D ON payment_link (confirmed_by_id)');
        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_code VARCHAR(30) NOT NULL, description VARCHAR(255) NOT NULL, quantity NUMERIC(18, 6) NOT NULL, unit_price NUMERIC(18, 6) NOT NULL, reference_price NUMERIC(18, 6) NOT NULL, raw JSON NOT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52EA1F098D9F6D38 ON order_item (order_id)');
        $this->addSql('ALTER TABLE commission ADD CONSTRAINT FK_1C650158B03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commission ADD CONSTRAINT FK_1C6501582D234F6A FOREIGN KEY (approved_by_id) REFERENCES app_user (id)');
        $this->addSql('ALTER TABLE audit_event ADD CONSTRAINT FK_3CE56E5010DAF24A FOREIGN KEY (actor_id) REFERENCES app_user (id)');
        $this->addSql('ALTER TABLE order_snapshot ADD CONSTRAINT FK_CDB5F784202D1EB2 FOREIGN KEY (commission_id) REFERENCES commission (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE adjustment ADD CONSTRAINT FK_89F97816202D1EB2 FOREIGN KEY (commission_id) REFERENCES commission (id)');
        $this->addSql('ALTER TABLE adjustment ADD CONSTRAINT FK_89F97816B03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment_link ADD CONSTRAINT FK_172F0E85202D1EB2 FOREIGN KEY (commission_id) REFERENCES commission (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment_link ADD CONSTRAINT FK_172F0E856F45385D FOREIGN KEY (confirmed_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F098D9F6D38 FOREIGN KEY (order_id) REFERENCES order_snapshot (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commission ADD CONSTRAINT commission_amounts_check CHECK (gross_amount > 0 AND deductions >= 0 AND net_amount > 0 AND net_amount = gross_amount - deductions)');
        $this->addSql('ALTER TABLE commission ADD CONSTRAINT commission_status_check CHECK (status IN (\'pending\', \'approved\', \'paid\'))');
        $this->addSql('ALTER TABLE commission ADD CONSTRAINT commission_approval_check CHECK ((status = \'pending\' AND approved_by_id IS NULL AND approved_at IS NULL) OR (status IN (\'approved\', \'paid\') AND approved_by_id IS NOT NULL AND approved_at IS NOT NULL AND approved_by_id <> created_by_id))');
        $this->addSql('ALTER TABLE adjustment ADD CONSTRAINT adjustment_amount_check CHECK (amount > 0 AND type IN (\'debt\', \'return\'))');
        $this->addSql('ALTER TABLE payment_link ADD CONSTRAINT payment_amount_check CHECK (amount > 0)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT item_amount_check CHECK (quantity >= 0 AND unit_price >= 0)');
        $this->addSql('CREATE INDEX commission_created_status_idx ON commission(created_at, status)');
        $this->addSql('CREATE INDEX audit_created_idx ON audit_event(created_at)');
        $this->addSql('CREATE INDEX audit_subject_idx ON audit_event(subject)');
        $this->addSql('CREATE INDEX adjustment_customer_idx ON adjustment(customer_code, commission_id)');
        $this->addSql('CREATE FUNCTION reject_historical_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION \'Historical record is immutable\'; END; $$');
        $this->addSql('CREATE TRIGGER audit_append_only BEFORE UPDATE OR DELETE ON audit_event FOR EACH ROW EXECUTE FUNCTION reject_historical_change()');
        $this->addSql('CREATE TRIGGER order_items_immutable BEFORE UPDATE OR DELETE ON order_item FOR EACH ROW EXECUTE FUNCTION reject_historical_change()');
        $this->addSql('CREATE FUNCTION guard_order_snapshot() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP = \'DELETE\' THEN RAISE EXCEPTION \'Order snapshots are immutable\'; END IF; IF (to_jsonb(NEW) - \'commission_id\') IS DISTINCT FROM (to_jsonb(OLD) - \'commission_id\') OR (OLD.commission_id IS NOT NULL AND NEW.commission_id IS DISTINCT FROM OLD.commission_id) THEN RAISE EXCEPTION \'Order snapshots are immutable\'; END IF; RETURN NEW; END; $$');
        $this->addSql('CREATE TRIGGER order_snapshot_immutable BEFORE UPDATE OR DELETE ON order_snapshot FOR EACH ROW EXECUTE FUNCTION guard_order_snapshot()');
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException('Contains financial and audit records. Restore a verified backup instead.');
    }
}
