expose_php=Off
display_errors=Off
log_errors=On
error_log=/proc/self/fd/2
date.timezone=UTC
memory_limit=256M
max_execution_time=60
session.save_path=/app/var/sessions
session.use_strict_mode=1
session.use_only_cookies=1
session.cookie_httponly=1
opcache.enable=1
opcache.validate_timestamps=0
